server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuncang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ""
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 5000
      idle-timeout: 0
      max-lifetime: 18000000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      database: 2
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
  mail:
    host: smtp.163.com
    username: xiao2397903439@163.com
    password: ZBUQ6j8f6jAUkE5d
    default-encoding: utf-8 #邮件内容的编码
    protocol: smtp

#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  type-aliases-package: com.xhz.yuncang.entity
#  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      #      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
